-- Tabla 1: datos crudos, exactamente como llegan de la API
CREATE TABLE IF NOT EXISTS raw_data (
    id SERIAL PRIMARY KEY,
    elevation FLOAT,
    aspect FLOAT,
    slope FLOAT,
    horizontal_distance_to_hydrology FLOAT,
    vertical_distance_to_hydrology FLOAT,
    horizontal_distance_to_roadways FLOAT,
    hillshade_9am FLOAT,
    hillshade_noon FLOAT,
    hillshade_3pm FLOAT,
    horizontal_distance_to_fire_points FLOAT,
    wilderness_area VARCHAR(50),
    soil_type VARCHAR(50),
    cover_type INTEGER,
    collected_at TIMESTAMP DEFAULT NOW()
);

-- Tabla 2: datos limpios (sin nulos, tipos correctos)
CREATE TABLE IF NOT EXISTS processed_data (
    id SERIAL PRIMARY KEY,
    elevation FLOAT,
    aspect FLOAT,
    slope FLOAT,
    horizontal_distance_to_hydrology FLOAT,
    vertical_distance_to_hydrology FLOAT,
    horizontal_distance_to_roadways FLOAT,
    hillshade_9am FLOAT,
    hillshade_noon FLOAT,
    hillshade_3pm FLOAT,
    horizontal_distance_to_fire_points FLOAT,
    wilderness_area VARCHAR(50),
    soil_type VARCHAR(50),
    cover_type INTEGER,
    processed_at TIMESTAMP DEFAULT NOW()
);

-- Tabla 3: datos listos para entrenar (con One-Hot Encoding aplicado)
CREATE TABLE IF NOT EXISTS training_data (
    id SERIAL PRIMARY KEY,
    elevation FLOAT,
    aspect FLOAT,
    slope FLOAT,
    horizontal_distance_to_hydrology FLOAT,
    vertical_distance_to_hydrology FLOAT,
    horizontal_distance_to_roadways FLOAT,
    hillshade_9am FLOAT,
    hillshade_noon FLOAT,
    hillshade_3pm FLOAT,
    horizontal_distance_to_fire_points FLOAT,
    -- Wilderness Area: 4 columnas binarias
    wilderness_area_1 INTEGER DEFAULT 0,
    wilderness_area_2 INTEGER DEFAULT 0,
    wilderness_area_3 INTEGER DEFAULT 0,
    wilderness_area_4 INTEGER DEFAULT 0,
    -- Soil Type: 40 columnas binarias
    soil_type_1 INTEGER DEFAULT 0,
    soil_type_2 INTEGER DEFAULT 0,
    soil_type_3 INTEGER DEFAULT 0,
    soil_type_4 INTEGER DEFAULT 0,
    soil_type_5 INTEGER DEFAULT 0,
    soil_type_6 INTEGER DEFAULT 0,
    soil_type_7 INTEGER DEFAULT 0,
    soil_type_8 INTEGER DEFAULT 0,
    soil_type_9 INTEGER DEFAULT 0,
    soil_type_10 INTEGER DEFAULT 0,
    soil_type_11 INTEGER DEFAULT 0,
    soil_type_12 INTEGER DEFAULT 0,
    soil_type_13 INTEGER DEFAULT 0,
    soil_type_14 INTEGER DEFAULT 0,
    soil_type_15 INTEGER DEFAULT 0,
    soil_type_16 INTEGER DEFAULT 0,
    soil_type_17 INTEGER DEFAULT 0,
    soil_type_18 INTEGER DEFAULT 0,
    soil_type_19 INTEGER DEFAULT 0,
    soil_type_20 INTEGER DEFAULT 0,
    soil_type_21 INTEGER DEFAULT 0,
    soil_type_22 INTEGER DEFAULT 0,
    soil_type_23 INTEGER DEFAULT 0,
    soil_type_24 INTEGER DEFAULT 0,
    soil_type_25 INTEGER DEFAULT 0,
    soil_type_26 INTEGER DEFAULT 0,
    soil_type_27 INTEGER DEFAULT 0,
    soil_type_28 INTEGER DEFAULT 0,
    soil_type_29 INTEGER DEFAULT 0,
    soil_type_30 INTEGER DEFAULT 0,
    soil_type_31 INTEGER DEFAULT 0,
    soil_type_32 INTEGER DEFAULT 0,
    soil_type_33 INTEGER DEFAULT 0,
    soil_type_34 INTEGER DEFAULT 0,
    soil_type_35 INTEGER DEFAULT 0,
    soil_type_36 INTEGER DEFAULT 0,
    soil_type_37 INTEGER DEFAULT 0,
    soil_type_38 INTEGER DEFAULT 0,
    soil_type_39 INTEGER DEFAULT 0,
    soil_type_40 INTEGER DEFAULT 0,
    -- Variable objetivo
    cover_type INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);
